# Generated by Django 6.0.2 on 2026-02-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dette',
            old_name='partenaire',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='dette',
            old_name='echeance',
            new_name='date_echeance',
        ),
    ]
